## 注意事项

1. `try`中可能会抛出多个异常,那么就可以使用多个`catch`来处理异常对象
2. 在`try`中产生了异常, 就会执行`catch`中的异常处理, 执行完`catch`中的逻辑, 继续执行之后的代码



![](https://pic.superbed.cn/item/5da46f0c451253d17887b0ae.jpg)

## finally代码块

1. 不能单独适用,  必须和`try...catch`一起使用
2. finally一般用于资源释放(资源回收),  `无论程序是否异常, finally 都要执行`





![](https://pic.superbed.cn/item/5da46fbe451253d17887be3a.jpg)

![](https://pic.superbed.cn/item/5da46ff3451253d17887c2d6.jpg)

![](https://pic.superbed.cn/item/5da47037451253d17887f49b.jpg)

![](https://pic.superbed.cn/item/5da47050451253d1788803f8.jpg)

![](https://pic.superbed.cn/item/5da47080451253d1788810a3.jpg)

![](https://pic.superbed.cn/item/5da470bd451253d178881fe0.jpg)























































